### ISSUE TITLE
Is it possible to `impl<T: Atom> Atom for Option<T>` to be added?

### ISSUE THREAD

**Issue by kkysen** [LukasKalbertodt/atomig#13]
`atomig` already has `impl Atom`s for `Option<NonNull<T>>` and `Option<NonZero*>` types, but it would be really nice if this could be extended to other `T`s that have niches.  I've sketched out a solution below that could maybe work, and [checked in godbolt that there's no overhead](https://godbolt.org/z/j9b8MnvoW).  What do you think?

```rust
use core::mem;
use core::ops::AddAssign;
use core::num::NonZeroU64;

pub trait Atom {
    type Repr;

    fn pack(self) -> Self::Repr;
    fn unpack(src: Self::Repr) -> Self;
}

impl<T> Atom for Option<T>
where 
    T: Atom,
    T: TryFrom<T::Repr>,
    T::Repr: Copy,
    T::Repr: From<u8>, // For 0 and 1
    T::Repr: AddAssign,
{
    type Repr = T::Repr;

    fn pack(self) -> Self::Repr {
        let niche = {
            // Guarantee we have a niche.
            assert!(mem::size_of::<Option<T>>() == mem::size_of::<T>());
            let zero = T::Repr::from(0);
            let one = T::Repr::from(1);
            // Since we checked there's a niche, this should terminate (assuming `TryFrom` is normal).
            let mut niche = zero;
            loop {
                if T::try_from(niche).is_err() {
                    break;
                }
                niche += one;
            }
            niche
        };
        self.map(T::pack).unwrap_or(niche)
    }

    fn unpack(src: Self::Repr) -> Self {
        src.try_into().ok()
    }
}

impl Atom for NonZeroU64 {
    type Repr = u64;

    fn pack(self) -> Self::Repr {
        self.get()
    }

    fn unpack(src: Self::Repr) -> Self {
        src.try_into().unwrap()
    }
}

#[no_mangle]
pub fn pack_u64(x: Option<NonZeroU64>) -> u64 {
    x.pack()
}

#[no_mangle]
pub fn unpack_u64(x: u64) -> Option<NonZeroU64> {
    Atom::unpack(x)
}

pub enum Enum {
    A,
    B,
    C,
}

impl Atom for Enum {
    type Repr = u8;

    fn pack(self) -> Self::Repr {
        self as _
    }

    fn unpack(src: Self::Repr) -> Self {
        src.try_into().unwrap()
    }
}

impl TryFrom<u8> for Enum {
    type Error = ();

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        Ok(match value {
            0 => Self::A,
            1 => Self::B,
            2 => Self::C,
            _ => return Err(()),
        })
    }
}

#[no_mangle]
pub fn pack_enum(x: Option<Enum>) -> u8 {
    x.pack()
}

#[no_mangle]
pub fn unpack_enum(x: u8) -> Option<Enum> {
    Atom::unpack(x)
}
```

Both `fn pack_{u64,enum}` compile to no-ops, so the `niche` loop is being fully optimized out.  And for `fn unpack_{u64,enum}` I'm not seeing asm, which I think means they have the same code as `fn {NonZeroU64,Enum}::unpack`.

The main annoying obstacle I see to this is that there is no `impl TryFrom<*mut T> for NonNull<T>`, even though there definitely could be (`NonNull::new` is this).  To get around this, some other trait could be added to `atomig` like `trait TryFromRepr` that we `impl` for `NonNull`, `NonZero*`, etc., but then users of `atomig` would have to `impl TryFromRepr` themselves, and it wouldn't work if crate A, depending on `atomig` and crate B, tried to use `Atomic<Option<b::B>>` even if `B: TryFrom<b::B::Repr>`.  Ideally, `std` would just add the `impl TryFrom<*mut T> for NonNull<T>`.

**Comment by LukasKalbertodt** [comment]
Hey there! That's a really interesting idea with out-of-the thinking! Thanks for also verifying in godbolt that this actually has no overhead, I would not have expected this. Of course, this only guarantees that for these two specific example types, where the compiler has the exact definition, there is no overhead. 

In generally, I'm unfortunately hesitant to merge something like this. It just feels a touch too hacky with the option to result in very surprising runtime behavior. Also think of debug builds, where a non optimized `pack` function with very large niche can be incredibly slow. The many somewhat random trait bounds on the impl are also not great.

Again, thanks for the idea and testing, but I don't think it's a fit for this library.
